# Generated by Django 3.2.3 on 2021-05-16 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=100)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('gmaps_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lead_type', models.CharField(max_length=100)),
                ('source', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='teams.location')),
            ],
        ),
    ]
