# Generated by Django 3.2.3 on 2021-05-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('teams', '0002_auto_20210516_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
