# Generated by Django 3.2.3 on 2021-05-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_resources_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leadtype', to='teams.leadtype'),
        ),
    ]
