# Generated by Django 3.2.3 on 2021-05-16 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20210516_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=100)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('gmaps_url', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lead_type', models.CharField(max_length=100)),
                ('source', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('proposed_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposed_location', to='teams.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_count', models.IntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='guests.proposedlead')),
                ('proposed_resource_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposed_resource_type', to='teams.resources')),
            ],
        ),
    ]
