# Generated by Django 3.2.3 on 2021-05-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210523_1303'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedavailability',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_lead', to='guests.proposedlead'),
        ),
        migrations.AlterField(
            model_name='proposedlead',
            name='lead_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposed_leadtype', to='teams.leadtype'),
        ),
    ]
