# Generated by Django 3.2.3 on 2021-05-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20210523_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedavailability',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='guests.proposedlead'),
        ),
    ]
